
export const products = [
    {
      sku: 'FLW001',
      name: 'Purple Haze',
      description: 'Classic cannabis flower with a fruity aroma.',
      quantity: 50,
      price: 30,
      category: 'Cannabis Flower',
      storeLocation: 'Aisle 1',
    },
    {
      sku: 'FLW002',
      name: 'Blue Dream',
      description: 'Popular cannabis flower known for its balanced effects.',
      quantity: 40,
      price: 35,
      category: 'Cannabis Flower',
      storeLocation: 'Aisle 1',
    },
    {
      sku: 'FLW003',
      name: 'Sour Diesel',
      description: 'Pungent cannabis flower with energizing effects.',
      quantity: 30,
      price: 40,
      category: 'Cannabis Flower',
      storeLocation: 'Aisle 1',
    },
    {
      sku: 'FLW004',
      name: 'White Widow',
      description: 'Well-known cannabis flower with a strong, earthy flavor.',
      quantity: 25,
      price: 45,
      category: 'Cannabis Flower',
      storeLocation: 'Aisle 1',
    },
    {
      sku: 'OIL001',
      name: 'THC Distillate Syringe',
      description: 'High-potency THC oil for vaping or dabbing.',
      quantity: 60,
      price: 50,
      category: 'THC Oil',
      storeLocation: 'Aisle 2',
    },
    {
      sku: 'OIL002',
      name: 'THC Cartridge - Berry',
      description: 'Pre-filled THC oil cartridge with a berry flavor.',
      quantity: 55,
      price: 55,
      category: 'THC Oil',
      storeLocation: 'Aisle 2',
    },
    {
      sku: 'OIL003',
      name: 'THC Tincture - Mint',
      description: 'Sublingual THC oil tincture with a refreshing mint taste.',
      quantity: 50,
      price: 60,
      category: 'THC Oil',
      storeLocation: 'Aisle 2',
    },
    {
      sku: 'EDB001',
      name: 'THC Gummies - Watermelon',
      description: 'Delicious THC-infused gummies with a watermelon flavor.',
      quantity: 70,
      price: 25,
      category: 'THC Edibles',
      storeLocation: 'Aisle 3',
    },
    {
      sku: 'EDB002',
      name: 'THC Chocolate Bar',
      description: 'Decadent chocolate bar infused with THC.',
      quantity: 65,
      price: 30,
      category: 'THC Edibles',
      storeLocation: 'Aisle 3',
    },
    {
      sku: 'EDB003',
      name: 'THC Capsules',
      description: 'Easy-to-swallow capsules containing a precise dose of THC.',
      quantity: 60,
      price: 35,
      category: 'THC Edibles',
      storeLocation: 'Aisle 3',
    },
    {
      sku: 'CBD001',
      name: 'CBD Isolate Tincture',
      description: 'Pure CBD oil tincture, THC-free.',
      quantity: 75,
      price: 40,
      category: 'CBD Oils',
      storeLocation: 'Aisle 4',
    },
    {
      sku: 'CBD002',
      name: 'Full-Spectrum CBD Oil',
      description: 'CBD oil containing a full range of cannabinoids.',
      quantity: 70,
      price: 45,
      category: 'CBD Oils',
      storeLocation: 'Aisle 4',
    },
    {
      sku: 'CBD003',
      name: 'CBD Vape Cartridge',
      description: 'CBD oil vape cartridge for convenient inhalation.',
      quantity: 65,
      price: 50,
      category: 'CBD Oils',
      storeLocation: 'Aisle 4',
    },
    {
      sku: 'CEDB001',
      name: 'CBD Gummies - Mixed Fruit',
      description: 'CBD-infused gummies with a variety of fruit flavors.',
      quantity: 80,
      price: 20,
      category: 'CBD Edibles',
      storeLocation: 'Aisle 5',
    },
    {
      sku: 'CEDB002',
      name: 'CBD Honey Sticks',
      description: 'CBD-infused honey sticks for a sweet treat.',
      quantity: 75,
      price: 25,
      category: 'CBD Edibles',
      storeLocation: 'Aisle 5',
    },
    {
      sku: 'CEDB003',
      name: 'CBD Protein Bar',
      description: 'Protein-packed bar infused with CBD.',
      quantity: 70,
      price: 30,
      category: 'CBD Edibles',
      storeLocation: 'Aisle 5',
    },
  ];
